# Import the Data

We are exploring StackOverflow Annual Developer survey data from 2019. The data is available at:
* https://insights.stackoverflow.com/survey in CSV format

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import pymongo
from pymongo import MongoClient
import json
from datetime import datetime

In [4]:
data = pd.read_csv("./data/developer_survey_2019/survey_results_public.csv")

In [5]:
data.shape

(88883, 85)

In [6]:
data.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

The data is pretty large. Consists of inputs from almost 89,000 developers. The data is multidimensinal. It has 85 columns. Since not all the columns will be used in our analysis we will trim down the dataset as much as we need.

# Data Cleaning

Right below we are eliminating the rows where Language Worked With column is not filled. This is a developer survey and we expect to have at least one language in that column.

In [7]:
cleaned_data = data[pd.notnull(data['LanguageWorkedWith'])]

In [8]:
# Below is convenient method to visualize all columns and their calues in jupyter notebook. Based on the below
#information we will decide on which columns to keep.
cleaned_data.iloc[1].to_dict()

{'Respondent': 2,
 'MainBranch': 'I am a student who is learning to code',
 'Hobbyist': 'No',
 'OpenSourcer': 'Less than once per year',
 'OpenSource': 'The quality of OSS and closed source software is about the same',
 'Employment': 'Not employed, but looking for work',
 'Country': 'Bosnia and Herzegovina',
 'Student': 'Yes, full-time',
 'EdLevel': 'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
 'UndergradMajor': nan,
 'EduOther': 'Taken an online course in programming or software development (e.g. a MOOC)',
 'OrgSize': nan,
 'DevType': 'Developer, desktop or enterprise applications;Developer, front-end',
 'YearsCode': nan,
 'Age1stCode': '17',
 'YearsCodePro': nan,
 'CareerSat': nan,
 'JobSat': nan,
 'MgrIdiot': nan,
 'MgrMoney': nan,
 'MgrWant': nan,
 'JobSeek': 'I am actively looking for a job',
 'LastHireDate': "I've never had a job",
 'LastInt': nan,
 'FizzBuzz': nan,
 'JobFactors': "Financial performance or funding status of the company or organization;Specific department or team I'd be working on;Languages, frameworks, and other technologies I'd be working with",
 'ResumeUpdate': 'Something else changed (education, award, media, etc.)',
 'CurrencySymbol': nan,
 'CurrencyDesc': nan,
 'CompTotal': nan,
 'CompFreq': nan,
 'ConvertedComp': nan,
 'WorkWeekHrs': nan,
 'WorkPlan': nan,
 'WorkChallenge': nan,
 'WorkRemote': nan,
 'WorkLoc': nan,
 'ImpSyn': nan,
 'CodeRev': nan,
 'CodeRevHrs': nan,
 'UnitTests': nan,
 'PurchaseHow': nan,
 'PurchaseWhat': nan,
 'LanguageWorkedWith': 'C++;HTML/CSS;Python',
 'LanguageDesireNextYear': 'C++;HTML/CSS;JavaScript;SQL',
 'DatabaseWorkedWith': nan,
 'DatabaseDesireNextYear': 'MySQL',
 'PlatformWorkedWith': 'Windows',
 'PlatformDesireNextYear': 'Windows',
 'WebFrameWorkedWith': 'Django',
 'WebFrameDesireNextYear': 'Django',
 'MiscTechWorkedWith': nan,
 'MiscTechDesireNextYear': nan,
 'DevEnviron': 'Atom;PyCharm',
 'OpSys': 'Windows',
 'Containers': 'I do not use containers',
 'BlockchainOrg': nan,
 'BlockchainIs': 'Useful across many domains and could change many aspects of our lives',
 'BetterLife': 'Yes',
 'ITperson': 'Yes',
 'OffOn': 'Yes',
 'SocialMedia': 'Instagram',
 'Extraversion': 'Online',
 'ScreenName': 'Username',
 'SOVisit1st': '2017',
 'SOVisitFreq': 'Daily or almost daily',
 'SOVisitTo': 'Find answers to specific questions;Learn how to do things I didnâ€™t necessarily look for',
 'SOFindAnswer': '3-5 times per week',
 'SOTimeSaved': 'Stack Overflow was much faster',
 'SOHowMuchTime': '11-30 minutes',
 'SOAccount': 'Yes',
 'SOPartFreq': 'A few times per month or weekly',
 'SOJobs': 'No, I knew that Stack Overflow had a job board but have never used or visited it',
 'EntTeams': "No, and I don't know what those are",
 'SOComm': 'Yes, somewhat',
 'WelcomeChange': 'Just as welcome now as I felt last year',
 'SONewContent': "Tech articles written by other developers;Industry news about technologies you're interested in;Tech meetups or events in your area;Courses on technologies you're interested in",
 'Age': 19.0,
 'Gender': 'Man',
 'Trans': 'No',
 'Sexuality': 'Straight / Heterosexual',
 'Ethnicity': nan,
 'Dependents': 'No',
 'SurveyLength': 'Appropriate in length',
 'SurveyEase': 'Neither easy nor difficult'}

Below is the filter mask we created containig all the columns we need for our analysis

In [9]:
column_mask = ["MainBranch", "Hobbyist", "Employment", "Country", "EdLevel", "YearsCode", "ConvertedComp", "JobSat", "JobSeek", "LanguageWorkedWith", "DatabaseWorkedWith", "WebFrameWorkedWith", "SOVisitFreq", "Age", "Gender"]

In [10]:
# Apply mask
simple_data = cleaned_data[column_mask]

In [11]:
simple_data

,MainBranch,Hobbyist,Employment,Country,EdLevel,YearsCode,ConvertedComp,JobSat,JobSeek,LanguageWorkedWith,DatabaseWorkedWith,WebFrameWorkedWith,SOVisitFreq,Age,Gender
0,I am a student who is learning to code,Yes,"Not employed, and not looking for work",United Kingdom,Primary/elementary school,4,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,SQLite,Django;Flask,A few times per month or weekly,14.0,Man
1,I am a student who is learning to code,No,"Not employed, but looking for work",Bosnia and Herzegovina,"Secondary school (e.g. American high school, G...",NaN,NaN,NaN,I am actively looking for a job,C++;HTML/CSS;Python,NaN,Django,Daily or almost daily,19.0,Man
2,"I am not primarily a developer, but I write co...",Yes,Employed full-time,Thailand,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)",3,8820.0,Slightly satisfied,"Iâ€™m not actively looking, but I am open to new...",HTML/CSS,PostgreSQL,NaN,A few times per week,28.0,Man
3,I am a developer by profession,No,Employed full-time,United States,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)",3,61000.0,Slightly satisfied,I am not interested in new job opportunities,C;C++;C#;Python;SQL,MySQL;SQLite,NaN,Daily or almost daily,22.0,Man
4,I am a developer by profession,Yes,Employed full-time,Ukraine,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)",16,NaN,Slightly dissatisfied,I am not interested in new job opportunities,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Django;Express;Flask;jQuery;React.js;Spring,Multiple times per day,30.0,Man
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88875,NaN,Yes,Employed part-time,Pakistan,"Secondary school (e.g. American high school, G...",1,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,NaN,Other(s):,I have never visited Stack Overflow (before to...,NaN,Man
88876,NaN,No,Employed full-time,Spain,"Secondary school (e.g. American high school, G...",18,NaN,NaN,NaN,HTML/CSS;JavaScript;Python,MySQL;PostgreSQL,Django;React.js,A few times per week,40.0,Man
88877,NaN,Yes,"Not employed, but looking for work",United States,Some college/university study without earning ...,38,NaN,NaN,NaN,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;W...,NaN,React.js,A few times per month or weekly,NaN,Man
88878,NaN,Yes,"Not employed, and not looking for work",Canada,Primary/elementary school,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,Firebase;SQLite,jQuery,A few times per week,NaN,Man
88882,NaN,Yes,"Not employed, and not looking for work",Spain,"Professional degree (JD, MD, etc.)",8,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,Django;jQuery;React.js,Daily or almost daily,18.0,Man

# Database Creation and Data Ingestion

We will be using MongoDB for our database.

In [12]:
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

## Create StackOverFlow database and ingest developers collection into the databse in the form of python dictionary

In [13]:
db = client.stack_overflow
developers = db.developers.find()

Iterate over simple_data DataFrame and add each row into stack_overflow database as a developer collection. Check for Nan values in "DatabaseWorkedWith" and "WebFrameWorkedWith" columns

In [14]:
for row in simple_data.itertuples():
    developer_dict = {}
    developer_dict["MainBranch"] = getattr(row, "MainBranch")
    developer_dict["Hobbyist"] = getattr(row, "Hobbyist")
    developer_dict["Employment"] = getattr(row, "Employment")
    developer_dict["Country"] = getattr(row, "Country")
    developer_dict["EdLevel"] = getattr(row, "EdLevel")
    developer_dict["YearsCode"] = getattr(row, "YearsCode")
    developer_dict["ConvertedComp"] = getattr(row, "ConvertedComp")
    developer_dict["JobSat"] = getattr(row, "JobSat")
    developer_dict["JobSeek"] = getattr(row, "JobSeek")
    developer_dict["LanguageWorkedWith"] = getattr(row, "LanguageWorkedWith").split(";")
    if pd.isna(getattr(row, "DatabaseWorkedWith")):
        developer_dict["DatabaseWorkedWith"] = None
    else:
        developer_dict["DatabaseWorkedWith"] = getattr(row, "DatabaseWorkedWith").split(";")
    if pd.isna(getattr(row, "WebFrameWorkedWith")):
        developer_dict["WebFrameWorkedWith"] = None
    else:
        developer_dict["WebFrameWorkedWith"] = getattr(row, "WebFrameWorkedWith").split(";")
    developer_dict["SOVisitFreq"] = getattr(row, "SOVisitFreq")
    developer_dict["Age"] = getattr(row, "Age")
    developer_dict["Gender"] = getattr(row, "Gender")
    db.developers.insert_one(developer_dict)